"use strict";
let cfg, data, startTime, scenarioIndex=0, promptIndex=0, blockIndex=0, ended=false, paused=false, agents={};
const el=id=>document.getElementById(id);
const canonical=v=>JSON.stringify(v && typeof v==='object' ? (Array.isArray(v)?v.map(sorted):sorted(v)):v);
function sorted(v){if(Array.isArray(v))return v.map(sorted);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,sorted(v[k])]));return v;}
const digest=async v=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical(v))))).map(x=>x.toString(16).padStart(2,'0')).join('');
const events=()=>data.events.events;
function log(type,extra={}){if(!data||ended)return;events().push({seq:events().length,t_ms:Math.floor(performance.now()-startTime),type,...extra});el('eventlog').textContent=JSON.stringify(events(),null,2);}
function privateData(v){if(v&&typeof v==='object')return Object.entries(v).some(([k,x])=>['contact','email','phone','full_name','consent_text','address'].includes(k.toLowerCase())||privateData(x));return typeof v==='string'&&(/[\w.+%-]+@[\w.-]+\.[A-Za-z]{2,}|\b(passport|ssn|consent_text)\b/i.test(v));}
function validate(value,schema){const types=Array.isArray(schema.type)?schema.type:[schema.type];const typeOk=t=>t===undefined||t==='null'&&value===null||t==='object'&&value!==null&&typeof value==='object'&&!Array.isArray(value)||t==='array'&&Array.isArray(value)||t==='string'&&typeof value==='string'||t==='integer'&&Number.isSafeInteger(value)||t==='number'&&typeof value==='number'&&Number.isFinite(value)||t==='boolean'&&typeof value==='boolean';if(!types.some(typeOk))throw Error('wrong type');if(schema.enum&&!schema.enum.some(x=>JSON.stringify(x)===JSON.stringify(value)))throw Error('unknown enum');if(value===null)return;if(typeof value==='string'&&(value.length<(schema.minLength||0)||schema.pattern&&!new RegExp(schema.pattern).test(value)))throw Error('invalid string');if(typeof value==='number'&&schema.minimum!==undefined&&value<schema.minimum)throw Error('below minimum');if(Array.isArray(value)&&schema.items)value.forEach(x=>validate(x,schema.items));else if(value&&typeof value==='object'){for(const k of schema.required||[])if(!(k in value))throw Error('missing field');for(const [k,x]of Object.entries(value)){if(schema.additionalProperties===false&&!(k in (schema.properties||{})))throw Error('unknown field');if(schema.properties?.[k])validate(x,schema.properties[k]);}}}
async function validateEnvelope(doc){if(!doc||Object.keys(doc).sort().join(',')!=='answers,events,schema,session'||doc.schema!==cfg.export_schema)throw Error('envelope mismatch');if(privateData(doc))throw Error('privacy quarantine');for(const k of ['session','events','answers'])validate(doc[k],cfg.schemas[k]);if(doc.session.synthetic!==true||doc.session.cohort!=='synthetic'||!doc.session.consent.given||doc.session.consent.version!==cfg.protocol.consent_version||doc.session.contract_sha256!==cfg.contract_sha256||doc.session.protocol_version!==cfg.protocol.protocol_version)throw Error('binding mismatch');if(doc.session.session_id!==doc.events.session_id||doc.session.session_id!==doc.answers.session_id)throw Error('session mismatch');let t=-1;doc.events.events.forEach((e,i)=>{if(e.seq!==i||e.t_ms<t)throw Error('sequence mismatch');t=e.t_ms;});if(new Set(doc.answers.responses.map(x=>x.measure)).size!==doc.answers.responses.length)throw Error('duplicate measure');return doc;}
const tasks=()=>cfg.scenarios.comprehension_scenarios.filter(s=>s.id.endsWith('-S1')&&s.measure!=='C5');
const blocks=()=>cfg.scenarios.approval_blocks.filter(b=>b.feasible);
function showTask(){el('scenario-card').hidden=false;el('response-box').hidden=false;const s=tasks()[scenarioIndex];el('scenario-title').textContent=s.measure+' / '+s.id;el('scenario-text').textContent=s.task+' Principal: '+s.principal+'; scope: '+s.scope;el('answer').value='';el('explanation').value='';log('prompt_displayed',{prompt_id:s.id});el('answer').focus();}
el('start').onclick=()=>{if(!cfg||!el('consent').checked||data)return;const id=Array.from(crypto.getRandomValues(new Uint8Array(6))).map(x=>'0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'[x%36]).join('');startTime=performance.now();data={schema:cfg.export_schema,session:{session_id:'S-'+id,participant_id:'P-'+id,role:el('role').value,protocol_version:cfg.protocol.protocol_version,contract_sha256:cfg.contract_sha256,cohort:'synthetic',synthetic:true,started_at:new Date().toISOString(),completed_at:null,excluded:null,consent:{given:true,version:cfg.protocol.consent_version}},events:{session_id:'S-'+id,events:[]},answers:{session_id:'S-'+id,responses:[]}};el('start').disabled=true;el('consent').disabled=true;el('role').disabled=true;el('withdraw').disabled=false;el('export').disabled=false;document.querySelectorAll('[data-fatigue]').forEach(b=>b.disabled=false);el('status').textContent='Synthetic dry run active; no human outcome will be claimed.';showTask();};
el('save-answer').onclick=()=>{if(!data||ended)return;const s=tasks()[scenarioIndex];const response={measure:s.measure,scenario_id:s.id,primary:{value:el('answer').value,explanation:el('explanation').value,latency_ms:Math.floor(performance.now()-startTime)-events().at(-1).t_ms},rater2:null,adjudicated:null};if(privateData(response)){el('status').textContent='Privacy warning: remove personal data before recording.';return;}data.answers.responses.push(response);log('answer',{prompt_id:s.id});scenarioIndex++;if(scenarioIndex<tasks().length)showTask();else{el('scenario-card').hidden=true;el('stop-card').hidden=false;agents=Object.fromEntries(cfg.protocol.mock_agents.map(a=>[a,'running']));renderAgents();log('prompt_displayed',{prompt_id:'C5-S1'});el('stop-request').focus();}};
function renderAgents(){el('agent-states').replaceChildren(...Object.entries(agents).map(([a,s])=>{const li=document.createElement('li');li.textContent=a+': '+s;return li;}));}
el('stop-request').onclick=()=>{if(ended||el('stop-request').disabled)return;el('stop-request').disabled=true;log('stop_requested');el('stop-status').textContent='Stop pending acknowledgement from mock agents';Object.keys(agents).forEach((a,i)=>{agents[a]='pending';setTimeout(()=>{if(ended)return;if(!(el('stuck').checked&&i===1))agents[a]='stopped';renderAgents();if(Object.values(agents).every(s=>s==='stopped')){log('stop_confirmed',{acknowledged:true,acknowledgements:Object.entries(agents).map(([agent_id,state])=>({agent_id,state}))});el('stop-status').textContent='Stop confirmed by all mock agents';el('continue').disabled=false;}},120+i*120);});renderAgents();setTimeout(()=>{if(!ended&&Object.values(agents).some(s=>s!=='stopped')){log('stop_failed',{acknowledged:false});el('stop-status').textContent='Stop failed: mock agent still pending';el('continue').disabled=false;}},1000);};
el('continue').onclick=()=>{if(ended||el('continue').disabled)return;el('stop-card').hidden=true;el('continue').disabled=true;startBlock();};
function startBlock(){if(blockIndex>=blocks().length){finish();return;}promptIndex=0;el('block-controls').hidden=false;log('block_started',{block_id:blocks()[blockIndex].block});showPrompt();}
function showPrompt(){const block=blocks()[blockIndex];if(promptIndex>=block.prompts.length){log('block_ended',{block_id:block.block});blockIndex++;startBlock();return;}const p=block.prompts[promptIndex];el('scenario-card').hidden=false;el('response-box').hidden=true;el('scenario-title').textContent='Approval '+p.prompt_id;el('scenario-text').textContent=p.actor+' requests '+p.action+'; scope '+p.scope+'; expiry '+p.expiry;log('prompt_displayed',{prompt_id:p.prompt_id,actor_shown:p.actor,action_shown:p.action,scope_shown:p.scope,expiry_shown:p.expiry!==null});el('scenario-actions').replaceChildren(...['approve','deny','abstain'].map(decision=>{const b=document.createElement('button');b.textContent=decision;b.onclick=()=>{if(paused||ended)return;log('decision',{prompt_id:p.prompt_id,decision});promptIndex++;showPrompt();};return b;}));}
el('pause').onclick=()=>{if(ended||paused)return;log('block_paused',{block_id:blocks()[blockIndex].block});paused=true;el('pause').disabled=true;el('resume').disabled=false;el('scenario-actions').querySelectorAll('button').forEach(b=>b.disabled=true);};
el('resume').onclick=()=>{if(ended||!paused)return;log('block_resumed',{block_id:blocks()[blockIndex].block});paused=false;el('pause').disabled=false;el('resume').disabled=true;el('scenario-actions').querySelectorAll('button').forEach(b=>b.disabled=false);};
function finish(){log('debrief_done');data.session.completed_at=new Date().toISOString();ended=true;el('scenario-card').hidden=true;el('block-controls').hidden=true;el('withdraw').disabled=true;document.querySelectorAll('[data-fatigue]').forEach(b=>b.disabled=true);el('status').textContent='Synthetic session complete. Export for Python validation; responses require independent grading.';}
el('withdraw').onclick=()=>{if(!data||ended)return;log('withdrawn');data.session.excluded='withdrawal';ended=true;el('scenario-card').hidden=true;el('stop-card').hidden=true;el('block-controls').hidden=true;el('withdraw').disabled=true;document.querySelectorAll('[data-fatigue]').forEach(b=>b.disabled=true);el('status').textContent='Withdrawn. No further events collected.';};
document.querySelectorAll('[data-fatigue]').forEach(b=>b.onclick=()=>{log('fatigue_report',{fatigue:b.dataset.fatigue});if(b.dataset.fatigue==='stop')el('withdraw').click();});
el('export').onclick=async()=>{try{await validateEnvelope(data);const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=data.session.session_id+'.export.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{el('status').textContent='Export refused: invalid or private data.';}};
el('import').onchange=async e=>{try{const f=e.target.files[0];if(!f||f.size>2000000)throw Error('size');await validateEnvelope(JSON.parse(await f.text()));el('import-status').textContent='Envelope schema/bindings OK. Python lifecycle validation still required.';}catch{el('import-status').textContent='Import FAILED: invalid, unbound or private envelope.';}};
fetch('browser-contract.json').then(r=>{if(!r.ok)throw Error('contract unavailable');return r.json();}).then(async x=>{cfg=x;if(await digest(cfg.protocol)!==cfg.contract_sha256)throw Error('contract digest mismatch');el('start').disabled=false;el('status').textContent='Frozen '+cfg.protocol.protocol_version+' loaded. Synthetic tooling only.';}).catch(()=>{el('status').textContent='BLOCKED: contract unavailable or invalid';});
