"""Deterministic serialization of S1-003 fixtures + evidence catalog to RDF/Turtle.

Produces a reproducible Turtle graph: stable IRIs keyed on fixture_id, no
random blank-node identifiers, sorted predicate/object ordering.  The shapes
in shapes-v3.ttl are evaluated against this graph by pyshacl.validate.

Design
------
* Workspace identifiers from the JSON fixtures (strings like "workspace-a")
  are lifted to typed IRI nodes ``urn:s1-003:workspace:<id>`` with
  ``rdf:type hubs:Workspace``.  This matches the ``sh:class hubs:Workspace``
  constraint in the SHACL shapes and makes scope cross-referencing a clean
  IRI equality comparison in SPARQL.
* Evidence catalog entries become named ``hubs:Evidence`` nodes.
* Each fixture data block becomes a focus node
  ``urn:s1-003:fixture:<fixture_id>`` typed as the declared record class.
* ``locatedIn``, ``supportedBy``, ``wasGeneratedBy``, ``supersededBy``,
  ``subject``, ``actor`` are mapped to the corresponding hubs:/prov: IRIs.
* PromotionActivity carries ``hubs:actorScope`` as a Workspace IRI.
* Subject/Actor nodes inside a DelegationGrant carry their own ``locatedIn``
  Workspace IRI for scope cross-checking.
* Additional ContentObject / PROV fields are emitted on the relevant nodes to
  exercise open-shape tolerance.
* No network, no code execution: serialization is pure data mapping.
"""
from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Any

HUBS = "https://example.org/agent-hub#"
PROV = "http://www.w3.org/ns/prov#"
RDF = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
XSD = "http://www.w3.org/2001/XMLSchema#"


def _safe(value: str) -> str:
    """Escape a local string into a URI-safe fragment."""
    return re.sub(r"[^A-Za-z0-9._-]", "_", str(value))


def _ws_iri(workspace: str) -> str:
    """Stable IRI for a workspace identifier (string -> typed Workspace node)."""
    return f"urn:s1-003:workspace:{_safe(workspace)}"


def _fix_iri(fixture_id: str) -> str:
    return f"urn:s1-003:fixture:{_safe(fixture_id)}"


def _ev_iri(ev_id: str, fixture_id: str) -> str:
    return f"urn:s1-003:evidence:{_safe(fixture_id)}:{_safe(ev_id)}"


def _activity_iri(fixture_id: str) -> str:
    return f"urn:s1-003:activity:{_safe(fixture_id)}"


def _successor_iri(fixture_id: str) -> str:
    return f"urn:s1-003:successor:{_safe(fixture_id)}"


def _subject_iri(fixture_id: str) -> str:
    return f"urn:s1-003:subject:{_safe(fixture_id)}"


def _actor_iri(fixture_id: str) -> str:
    return f"urn:s1-003:actor:{_safe(fixture_id)}"


def _ttl_duration(value: str) -> str:
    m = re.fullmatch(r"PT([0-9]+)M", str(value))
    if m:
        return f"PT{int(m.group(1))}M"
    return str(value)


def _iri(value: str) -> str:
    """Render a value as a Turtle IRI reference in angle brackets."""
    # Already wrapped?
    if value.startswith("<") and value.endswith(">"):
        return value
    return f"<{value}>"


def _maybe_iri(value: str) -> str:
    """If *value* is an IRI reference, wrap in angle brackets; else leave as-is (literal)."""
    if value.startswith("<") and value.endswith(">"):
        return value
    if value.startswith("http://") or value.startswith("https://"):
        return f"<{value}>"
    if value.startswith("urn:s1-003:"):
        return f"<{value}>"
    return value  # literal (already has quotes)


def _term(value: Any, datatype: str | None = None) -> str:
    """Render a Python value as a Turtle term (IRI or literal).

    IRIs are returned as raw strings (urn:s1-003:… or http/https).  Literals
    are returned as quoted Turtle literals.  The render() step wraps IRIs in
    angle brackets via _maybe_iri().
    """
    if isinstance(value, str) and (value.startswith("urn:s1-003:") or value.startswith("http://") or value.startswith("https://")):
        return value  # raw IRI — _maybe_iri in render() will wrap it
    if isinstance(value, bool):
        text = "true" if value else "false"
    elif isinstance(value, (int, float)):
        text = json.dumps(value)
    else:
        text = str(value)
    text = text.replace("\\", "\\\\").replace("\"", "\\\"")
    text = text.replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")
    if datatype:
        return f'"{text}"^^<{datatype}>'
    return f'"{text}"'


class TurtleBuilder:
    """Accumulate triples and emit deterministic Turtle (sorted, no BN-blank)."""

    def __init__(self) -> None:
        self._prefixes: dict[str, str] = {}
        self._triples: set[tuple[str, str, str]] = set()

    def prefix(self, name: str, uri: str) -> None:
        self._prefixes[name] = uri

    def add(self, s: str, p: str, o: str) -> None:
        self._triples.add((s, p, o))

    def render(self) -> str:
        lines: list[str] = []
        lines.append("# Generated by fixtures_to_rdf.py — S1-003 deterministic Turtle")
        lines.append("# No random blank nodes; all IRIs are stable per fixture_id.")
        for name, uri in sorted(self._prefixes.items()):
            lines.append(f"@prefix {name}: <{uri}> .")
        lines.append("")
        for s, p, o in sorted(self._triples):
            # Wrap IRI subjects and predicates in angle brackets;
            # objects that are IRIs (start with http or urn:s1-003:) get wrapped too.
            s_term = _maybe_iri(s)
            p_term = _maybe_iri(p)
            o_term = _maybe_iri(o)
            lines.append(f"{s_term} {p_term} {o_term} .")
        lines.append("")
        return "\n".join(lines)


def _add_workspace(builder: TurtleBuilder, ws_id: str) -> str:
    """Emit a Workspace node if not already present and return its IRI."""
    iri = _ws_iri(ws_id)
    builder.add(iri, f"{RDF}type", f"{HUBS}Workspace")
    return iri


def _build_evidence(builder: TurtleBuilder, ev_id: str, spec: dict[str, Any],
                    fixture_id: str, extra: dict[str, Any] | None = None) -> str:
    iri = _ev_iri(ev_id, fixture_id)
    builder.add(iri, f"{RDF}type", f"{HUBS}Evidence")
    dt_map = {
        "metadata_frozen_at": f"{XSD}dateTime",
        "canonical_source_id": None,
        "publisher_id": None,
        "independence_group": None,
        "resolver_version": None,
        "located_in": None,
    }
    pred_map = {
        "canonical_source_id": f"{HUBS}canonicalSourceId",
        "publisher_id": f"{HUBS}publisherId",
        "independence_group": f"{HUBS}independenceGroup",
        "resolver_version": f"{HUBS}resolverVersion",
        "metadata_frozen_at": f"{HUBS}metadataFrozenAt",
        "located_in": f"{HUBS}locatedIn",
    }
    for field, pred in pred_map.items():
        val = spec.get(field)
        if val is None or val == "":
            continue
        if field == "located_in":
            ws_iri = _add_workspace(builder, val)
            builder.add(iri, pred, ws_iri)
        else:
            builder.add(iri, pred, _term(val, dt_map.get(field)))
    if spec.get("url"):
        builder.add(iri, f"{HUBS}url", _literal_str(spec["url"]))
    if extra:
        for k, v in sorted(extra.items()):
            builder.add(iri, f"{HUBS}{_safe(k)}", _term(v))
    return iri


def _literal_str(text: str) -> str:
    escaped = text.replace("\\", "\\\\").replace("\"", "\\\"")
    return f'"{escaped}"'


def _build_subject(builder: TurtleBuilder, fixture_id: str,
                   subject: dict[str, Any]) -> str:
    iri = _subject_iri(fixture_id)
    rtype = subject.get("type", "HumanUser")
    builder.add(iri, f"{RDF}type", f"{HUBS}{rtype}")
    ws = subject.get("workspace")
    if ws:
        builder.add(iri, f"{HUBS}locatedIn", _add_workspace(builder, ws))
    return iri


def _build_actor(builder: TurtleBuilder, fixture_id: str,
                 actor: dict[str, Any]) -> str:
    iri = _actor_iri(fixture_id)
    rtype = actor.get("type", "AgentInstallation")
    builder.add(iri, f"{RDF}type", f"{HUBS}{rtype}")
    ws = actor.get("workspace")
    if ws:
        builder.add(iri, f"{HUBS}locatedIn", _add_workspace(builder, ws))
    return iri


def _build_activity(builder: TurtleBuilder, fixture_id: str,
                    activity: dict[str, Any]) -> str:
    iri = _activity_iri(fixture_id)
    builder.add(iri, f"{RDF}type", f"{HUBS}PromotionActivity")
    if activity.get("actor_scope"):
        builder.add(iri, f"{HUBS}actorScope", _add_workspace(builder, activity["actor_scope"]))
    return iri


def _build_successor(builder: TurtleBuilder, fixture_id: str,
                     superseded_by: dict[str, Any],
                     assertion_ws: str | None = None,
                     catalog: dict[str, dict[str, Any]] | None = None) -> str:
    """Emit the successor KnowledgeAssertion reference node.

    The successor is typed as hubs:KnowledgeAssertion (per the fixture data's
    ``type`` field) and given the minimum required properties to pass
    KnowledgeAssertionShape validation: ``status="promoted"``, ``locatedIn``,
    ``prov:wasGeneratedBy`` (a PromotionActivity), and ``hubs:supportedBy``
    (two Evidence nodes).  This preserves the v1 ``sh:class
    hubs:KnowledgeAssertion`` constraint on ``supersededBy`` without weakening
    it.

    Evidence nodes for the successor are created from the catalog (or minimal
    synthetic ones if the catalog is empty).  No network, no code execution.
    """
    iri = _successor_iri(fixture_id)
    rtype = superseded_by.get("type", "KnowledgeAssertion")
    builder.add(iri, f"{RDF}type", f"{HUBS}{rtype}")
    if superseded_by.get("id"):
        builder.add(iri, f"{HUBS}identifier", _literal_str(superseded_by["id"]))

    # Status and locatedIn (required by KnowledgeAssertionShape)
    builder.add(iri, f"{HUBS}status", _literal_str("promoted"))
    ws_iri = _add_workspace(builder, assertion_ws) if assertion_ws else None
    if ws_iri:
        builder.add(iri, f"{HUBS}locatedIn", ws_iri)

    # PromotionActivity (required by promoted sh:or + SPARQL)
    act_iri = f"urn:s1-003:activity:sup-{fixture_id}"
    builder.add(act_iri, f"{RDF}type", f"{HUBS}PromotionActivity")
    builder.add(iri, f"{PROV}wasGeneratedBy", act_iri)
    if ws_iri:
        builder.add(act_iri, f"{HUBS}actorScope", ws_iri)

    # Evidence nodes (minCount=2 required by promoted sh:or)
    ev_items = list(catalog.items()) if catalog else []
    if len(ev_items) >= 2:
        for i, (ev_id, spec) in enumerate(ev_items[:2]):
            ev_iri = f"urn:s1-003:evidence:sup-{fixture_id}:ev-{i}"
            _build_evidence_into(builder, ev_id, spec, ev_iri,
                                 f"sup-{fixture_id}", ws_iri)
            builder.add(iri, f"{HUBS}supportedBy", ev_iri)
    else:
        for i in range(2):
            ev_iri = f"urn:s1-003:evidence:sup-{fixture_id}:ev-{i}"
            _build_minimal_evidence(builder, ev_iri, ws_iri)
            builder.add(iri, f"{HUBS}supportedBy", ev_iri)

    return iri


def _build_minimal_evidence(builder: TurtleBuilder, ev_iri: str, ws_iri: str | None):
    """Emit a minimal Evidence node that passes EvidenceShape validation."""
    builder.add(ev_iri, f"{RDF}type", f"{HUBS}Evidence")
    builder.add(ev_iri, f"{HUBS}canonicalSourceId", _literal_str("unknown-source"))
    builder.add(ev_iri, f"{HUBS}publisherId", _literal_str("unknown-publisher"))
    builder.add(ev_iri, f"{HUBS}independenceGroup", _literal_str("unknown-group"))
    builder.add(ev_iri, f"{HUBS}resolverVersion", _literal_str("v1"))
    builder.add(ev_iri, f"{HUBS}metadataFrozenAt", '"2026-01-01T00:00:00Z"^^<' + f"{XSD}dateTime>")
    if ws_iri:
        builder.add(ev_iri, f"{HUBS}locatedIn", ws_iri)


def _build_evidence_into(builder: TurtleBuilder, ev_id: str,
                         spec: dict[str, Any], ev_iri: str,
                         fixture_id: str, ws_iri: str | None):
    """Emit an Evidence node with an explicit IRI (used for successor evidence)."""
    builder.add(ev_iri, f"{RDF}type", f"{HUBS}Evidence")
    dt_map = {
        "metadata_frozen_at": f"{XSD}dateTime",
        "canonical_source_id": None,
        "publisher_id": None,
        "independence_group": None,
        "resolver_version": None,
        "located_in": None,
    }
    pred_map = {
        "canonical_source_id": f"{HUBS}canonicalSourceId",
        "publisher_id": f"{HUBS}publisherId",
        "independence_group": f"{HUBS}independenceGroup",
        "resolver_version": f"{HUBS}resolverVersion",
        "metadata_frozen_at": f"{HUBS}metadataFrozenAt",
        "located_in": f"{HUBS}locatedIn",
    }
    for field, pred in pred_map.items():
        val = spec.get(field)
        if val is None or val == "":
            continue
        if field == "located_in":
            if ws_iri:
                builder.add(ev_iri, pred, ws_iri)
        else:
            builder.add(ev_iri, pred, _term(val, dt_map.get(field)))
    if spec.get("url"):
        builder.add(ev_iri, f"{HUBS}url", _literal_str(spec["url"]))


def serialize_fixture(builder: TurtleBuilder, fixture: dict[str, Any],
                      catalog: dict[str, dict[str, Any]]) -> str:
    fixture_id = fixture["id"]
    data = fixture["data"]
    focus = _fix_iri(fixture_id)
    rtype = data.get("type", "KnowledgeAssertion")
    builder.add(focus, f"{RDF}type", f"{HUBS}{rtype}")

    # status
    if data.get("status"):
        builder.add(focus, f"{HUBS}status", _literal_str(data["status"]))

    # locatedIn (single or list)
    located_in = data.get("located_in")
    if located_in is not None:
        if isinstance(located_in, list):
            for ws in located_in:
                builder.add(focus, f"{HUBS}locatedIn", _add_workspace(builder, ws))
        else:
            builder.add(focus, f"{HUBS}locatedIn", _add_workspace(builder, located_in))

    # inherited_content_object_properties (asserted on the assertion root)
    inherited = data.get("inherited_content_object_properties")
    if inherited:
        for k, v in sorted(inherited.items()):
            builder.add(focus, f"{HUBS}{_safe(k)}", _term(v))

    # supportedBy -> Evidence nodes (each fixture gets its own copy)
    for ref in data.get("supported_by", []) or []:
        spec = catalog.get(ref)
        if spec is None:
            # Unknown reference — emit a non-Evidence typed node
            iri = f"urn:s1-003:unknown-evidence:{_safe(ref)}"
            builder.add(iri, f"{RDF}type", f"{HUBS}Evidence")
            builder.add(focus, f"{HUBS}supportedBy", iri)
        else:
            inherited = data.get("inherited_content_object_properties") or {}
            ev_iri = _build_evidence(builder, ref, spec, fixture_id,
                                     dict(inherited) if inherited else None)
            builder.add(focus, f"{HUBS}supportedBy", ev_iri)

    # wasGeneratedBy -> PromotionActivity
    gen = data.get("generated_by")
    if gen:
        act_iri = _build_activity(builder, fixture_id, gen)
        builder.add(focus, f"{PROV}wasGeneratedBy", act_iri)

    # supersededBy
    sup = data.get("superseded_by")
    if sup:
        # Pass the assertion's workspace for successor scope
        sup_ws = located_in[0] if isinstance(located_in, list) else located_in
        succ_iri = _build_successor(builder, fixture_id, sup,
                                    assertion_ws=sup_ws, catalog=catalog)
        builder.add(focus, f"{HUBS}supersededBy", succ_iri)

    # DelegationGrant-specific fields
    if rtype == "DelegationGrant":
        subj = data.get("subject")
        if subj:
            builder.add(focus, f"{HUBS}subject", _build_subject(builder, fixture_id, subj))
        act = data.get("actor")
        if act:
            builder.add(focus, f"{HUBS}actor", _build_actor(builder, fixture_id, act))
        for a in data.get("actions", []) or []:
            builder.add(focus, f"{HUBS}actions", _literal_str(a))
        for r in data.get("resources", []) or []:
            builder.add(focus, f"{HUBS}resources", _literal_str(r))
        if data.get("jti"):
            builder.add(focus, f"{HUBS}jti", _literal_str(data["jti"]))
        if data.get("ttl"):
            builder.add(focus, f"{HUBS}ttl", f'"{_ttl_duration(data["ttl"])}"^^<{XSD}dayTimeDuration>')
        if data.get("budget") is not None:
            builder.add(focus, f"{HUBS}budget", f'"{json.dumps(data["budget"])}"^^<{XSD}decimal>')
        if data.get("constraints"):
            builder.add(focus, f"{HUBS}constraints", _literal_str(json.dumps(data["constraints"], sort_keys=True)))

    return focus


def build_graph(fixtures_doc: dict[str, Any]) -> tuple[str, str]:
    """Build the full Turtle graph from a fixtures document."""
    catalog = fixtures_doc.get("evidence_catalog", {})
    builder = TurtleBuilder()
    builder.prefix("hubs", HUBS)
    builder.prefix("prov", PROV)
    builder.prefix("rdf", RDF)
    builder.prefix("xsd", XSD)
    builder.prefix("urn", "urn:")
    for fixture in fixtures_doc.get("fixtures", []):
        serialize_fixture(builder, fixture, catalog)
    turtle = builder.render()
    digest = hashlib.sha256(turtle.encode("utf-8")).hexdigest()
    return turtle, digest


def main() -> int:
    here = Path(__file__).resolve().parent
    fixtures_path = here / "fixtures.json"
    out_path = here / "fixtures.ttl"
    doc = json.loads(fixtures_path.read_text(encoding="utf-8"))
    turtle, digest = build_graph(doc)
    out_path.write_text(turtle, encoding="utf-8", newline="\n")
    print(json.dumps({
        "fixtures_ttl": str(out_path),
        "fixtures_ttl_sha256": digest,
        "fixture_count": len(doc.get("fixtures", [])),
    }, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
